import PDFDocument from 'pdfkit'


export const generatePdf = async (data) => {
    return new Promise((resolve, reject) => {
        // Create a new PDF document (A4 size) with metadata for the generated file
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Author: 'CortexAI',
                Title: data.title,
                Creator: 'CortexAI'
            }
        })

        const chucks = []
        // returns an event, here we get chunks of document and we add it in chucks = []
        doc.on("data", (chuck) => chucks.push(chuck))
        // concatinating the document chuck
        doc.on("end", () => resolve(Buffer.concat(chucks)))
        // if any error occure we reject the promise
        doc.on("error", () => reject)
        // adding data in document which triggers the required events
        // adding title
        doc
            .fontSize(28)
            .text(data.title, { align: 'center' })
            .fillColor("#111827")

        if (data.subtitle) doc.moveDown(0.5)

        // adding subtitle
        doc
            .fontSize(12)
            .text(data.subtitle, { align: 'center' })
            .fillColor("#6B7280")
        doc.moveDown(2)

        // adding sections
        data?.sections?.forEach(s => {
            doc
                .fontSize(18)
                .text(s.heading)
                .fillColor("#111827")
            doc.moveDown(0.5)

            s?.points?.forEach(p => {
                doc
                    .fontSize(12)
                    .text("• " + p, { lineGap: 5 })
                    .fillColor("#374151")
            })
            doc.moveDown()
        });
        doc.moveDown()

        // adding footer
        doc
            .fontSize(10)
            .text("Generated By CortexAI", { align: 'center' })
            .fillColor("#9CA3AF")

        doc.end()
    })
}